#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# User specific environment and startup programs
export TERMINAL=foot
export BROWSER=firefox
export EDITOR=nvim
export PAGER=most
export FILEMANAGER="$TERMINAL nnn"

# define XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

# set nnn to use trash-cli instead of rm -rf
export NNN_TRASH=1

# Enable wayland in firefox
export MOZ_ENABLE_WAYLAND=1

# Set gtk3 theme
export GTK_THEME=rose-pine-gtk
